### ISSUE TITLE
Use with `react-hot-loader`

### ISSUE THREAD

**Issue by iam4x** [goatslacker/alt#29]
Using alt with `react-hot-loader` loader in webpack, throw me random errors:

> Cannot not apply hot update to users.jsx: A store named UserStore already exists, double check your store names or pass in your own custom identifier for each store

I couldn't find what isn't working, went through this issue: https://github.com/moreartyjs/todomvc-moreartyjs/issues/2

Maybe something with the context?

**Comment by goatslacker** [comment]
It sounds like it's recreating the stores which is not a good thing. I'll take a closer look at this. If you have any code you can share please do :)

**Comment by iam4x** [comment]
https://github.com/iam4x/isomorphic-flux-boilerplate

Edit `app/component/users.jsx` with changing something in `render()` twice, it will be thrown in the console.

**Comment by frederickfogerty** [comment]
Would love for this to work, this is one of the major pains with react-hot-loader and alt. It reloads the relevant changed scripts so I thought it just couldn’t be fixed easily.


Frederick FogertyChief Front End Engineer • Integratorz Ltd.




m: 021 025 66091

s: frederick.fogerty

**Comment by goatslacker** [comment]
So it's a webpack bug:

https://github.com/webpack/webpack/issues/826

Let me think of ways to get around this in the meantime

**Comment by gaearon** [comment]
Yeah it's a Webpack bug. It's been annoying for months but I just got around to isolating it yesterday. Hopefully the fix is in the works!

**Comment by goatslacker** [comment]
Fixed by webpack :)

**Comment by gaearon** [comment]
You'll need to update Webpack to 1.7.0 to get the fix.

**Comment by bizmurr** [comment]
Hmm.. I am still receiving this error on Webpack 1.7.3, any thoughts @gaearon @goatslacker @iam4x?

**Comment by frederickfogerty** [comment]
Double check you are on the latest version - ever since I upgraded to 1.7 I haven't had this issue

**Comment by bizmurr** [comment]
Yeah, I am on 1.7.3 and still get the error when I make some code changes to a Store and then save, is this a different issue entirely?

**Comment by gaearon** [comment]
The original bug is about changing the component:

>Edit app/component/users.jsx with changing something in render() twice, it will be thrown in the console.

If you make changes *in the store*, there's nothing RHL can do: it doesn't know how to handles updates in an Alt store (at least not just yet :-). It only updates components, and files which are `require`d only by components. So yeah, changing the store will throw app into an inconsistent state and you need to either manually refresh, or use `hot/dev-server` instead of `hot/only-dev-server` to refresh automatically.

**Comment by bizmurr** [comment]
Ah I see, thanks for the clarification!

**Comment by goatslacker** [comment]
Actually let me open a new ticket.

**Comment by goatslacker** [comment]
#85
